// Autogenerated, do not edit. All changes will be lost.

/// <reference path="../node_modules/phaser/typescript/p2.d.ts" />
/// <reference path="../node_modules/phaser/typescript/phaser.comments.d.ts" />
/// <reference path="../node_modules/phaser/typescript/pixi.comments.d.ts" />
/// <reference path="../node_modules/retyped-jasmine-tsd-ambient/jasmine.d.ts" />